config/routes.rb
Rails.application.routes.draw do
  get 'simple_pages/about'
  get 'simple_pages/contact'
  get 'simple_pages/index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'simple_pages#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/simple_pages_controller.rb
class SimplePagesController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/simple_pages_helper.rb
module SimplePagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Sample App</title>

  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css">
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>

  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>

  <meta name="viewport" content="width=device-width, initial-scale=1">
  <%= csrf_meta_tags %>
</head>

<nav>
  <ul>
    <li><%= link_to "Home", root_path %></li>
    <li><%= link_to "About", simple_pages_about_path %></li>
    <li><%= link_to "Contact", simple_pages_contact_path %></li>
  </ul>
</nav>

<%= yield %>

<footer class="footer">
  &copy; 2018 Bike Berlin
</footer>

</body>
</html>

app/views/simple_pages/about.html.erb
<h1>About</h1>
<p>This website offers you Berlin's best used bikes!</p>

app/views/simple_pages/contact.html.erb
<h1>Contact</h1>
<p>Niels Jaeger</p>
<p>Beinerstr. 10</p>
<p>65375 Oestrich-Winkel</p>

app/views/simple_pages/index.html.erb
<h1>Welcome to Bike Berlin</h1>
<%= image_tag("nielsjaeger.jpg", class:"img-responsive") %>
<h2>Your source for used bikes in Berlin</h2>